
package br.com.agmg.soapexample.webservice.stubcode;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookCatalog", targetNamespace = "http://www.agmg.soapexample.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookCatalog {


    /**
     * 
     * @param book
     */
    @WebMethod(action = "add_book")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.AddBookResponse")
    @Action(input = "add_book", output = "http://www.agmg.soapexample.com.br/BookCatalog/addBookResponse")
    public void addBook(
        @WebParam(name = "Book", targetNamespace = "")
        Book book);

    /**
     * 
     * @param isbn
     * @return
     *     returns br.com.agmg.webservice.stubcode.Book
     * @throws InvalidBookReference_Exception
     */
    @WebMethod(action = "get_book")
    @WebResult(name = "Book", targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.GetBookResponse")
    @Action(input = "get_book", output = "http://www.agmg.soapexample.com.br/BookCatalog/getBookResponse", fault = {
        @FaultAction(className = InvalidBookReference_Exception.class, value = "http://www.agmg.soapexample.com.br/BookCatalog/getBook/Fault/InvalidBookReference")
    })
    public Book getBook(
        @WebParam(name = "Isbn", targetNamespace = "")
        String isbn)
        throws InvalidBookReference_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.agmg.webservice.stubcode.Book>
     */
    @WebMethod(action = "get_books")
    @WebResult(name = "Book", targetNamespace = "")
    @RequestWrapper(localName = "getBooks", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.GetBooks")
    @ResponseWrapper(localName = "getBooksResponse", targetNamespace = "http://www.agmg.soapexample.com.br", className = "br.com.agmg.webservice.stubcode.GetBooksResponse")
    @Action(input = "get_books", output = "http://www.agmg.soapexample.com.br/BookCatalog/getBooksResponse")
    public List<Book> getBooks();

}
